# Simple Python CI workflow for conf-import
# Runs on push and pull request to main
name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dnspython requests
    - name: Run tests
      run: |
        if [ -d tests ]; then
          python -m unittest discover -s tests
        else
          echo "No tests directory found."
        fi
